apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description
  description: The Petstore is an example API used to show features of the OpenAPI spec.
  annotations:
    backstage.io/techdocs-ref: https://github.com/kumarmunish/backstage-poc/tree/main/
    github.com/project-slug: kumarmunish/backstage-poc
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: team-c
  providesApis:
    - petstore
    - spotify
